# Generated by Django 2.2 on 2019-04-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarlMap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='long_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='year',
            field=models.IntegerField(default=2019),
        ),
    ]
